project:
  name: quickstart-cloudbees-core
  owner: dschott@cloudbees.com
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
  regions:
#  - us-east-1
#  - us-east-2
  - us-west-2
#  - eu-west-1
#  - ca-central-1
  parameters:
    RemoteAccessCIDR: 10.0.0.0/16
    QSS3BucketName: tcat-quickstart-cloudbees-core-uswest1243
    QSS3BucketRegion: 'us-west-2'
    AvailabilityZones: $[taskcat_genaz_3]
  template: templates/cloudbees-core-existing-vpc.template.yaml
tests:
  default:
    regions:
    - us-west-2
